#!/bin/sh

set -e

while getopts "pc" opt; do
    case $opt in
      p)
         ARGS="-d:NYTProf"
         ;;
      c)
         ARGS="-MDevel::Cover"
         ;;
    esac
done
shift $(($OPTIND - 1))

TZ=GMT

START_DATE=${1:-"2010-08-18 06:00:00"}
END_DATE=${2:-"2010-09-17 00:00:00"}


nice -n 19 perl $ARGS $TRADER_HOME/data/fxcm/servers/Trader/Trader.pl --class=UnitTest --notifier=UnitTest --startDate="$START_DATE" --endDate="$END_DATE" --expectedTradesFile=trades.xag --verbose
